server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.111:8848
    sentinel:
      transport:
        dashboard: 192.168.1.111:8080
        port: 8719
        clientIp: 192.168.1.109

service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对feign的支持, 关键项
feign:
  sentinel:
    enabled: true
